# ESO bu manifest'i okuyup Vault'tan çeker,
# "product-service-secrets" adında bir K8s Secret oluşturur.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product-service-secret
  namespace: devops-arena
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: product-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: devops-arena/product-service
        property: DATABASE_URL
